mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :tag => '4.5.1'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :tag => '1.8.0'

mod 'vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo',
  :tag => '1.2.0'

mod 'apache',
  :git => 'https://github.com/puppetlabs/puppetlabs-apache',
  :tag => '1.4.0'
  
mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat',
  :tag => '1.2.0'

mod 'postgresql',
  :git => 'https://github.com/puppetlabs/puppetlabs-postgresql',
  :tag => '4.3.0'

mod 'check_run',
  :git => 'https://bitbucket.org/landcareresearch/puppet-checkrun',
  :tag => 'v0.2.5'

mod 'beansbooks',
  #:git => 'file:///home/spethm/Work/MonkyGames/admin/puppet-beansbooks',
  :git => 'https://github.com/Conzar/puppet-beansbooks',
  :branch => 'master'
